//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTodoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public System.Guid Id { get; set; }
        public int Seq { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public System.Guid TypeId { get; set; }
        public string Status { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
    }
}
